parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    EmpireDesAmis\SecurityAuthenticatorBundle\:
        resource: '../src/'

    EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebase:
        alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebase

    EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\LogIn\LogInFirebaseInterface:
        alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\LogIn\LogInFirebase
